# Generated by Django 2.1b1 on 2019-02-27 13:24

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('IsEnabled', models.BooleanField(default=True, verbose_name='Enabled')),
                ('CreatedAt', models.DateTimeField(auto_now_add=True, verbose_name='Created At')),
                ('LastModified', models.DateTimeField(auto_now=True, verbose_name='Last Modified')),
                ('Lang', models.CharField(max_length=2, verbose_name='Language')),
                ('ProfileInfo', models.TextField(blank=True, verbose_name='Profile Info')),
                ('MailNotification', models.BooleanField(default=True, verbose_name='Mail notification')),
                ('StayLoggedIn', models.BooleanField(default=False, verbose_name='Stay Logged In')),
                ('Role', models.CharField(choices=[('D', 'Default'), ('S', 'SuperUser'), ('A', 'Administrator'), ('R', 'ReadOnly')], default='D', max_length=1, verbose_name='Role')),
                ('LoginCount', models.IntegerField(default=0)),
                ('IsUser', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
