# Generated by Django 2.0 on 2020-03-23 17:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('designer', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='taskProperty',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('IsEnabled', models.BooleanField(default=True, verbose_name='Enabled')),
                ('CreatedAt', models.DateTimeField(auto_now_add=True, verbose_name='Created At')),
                ('LastModified', models.DateTimeField(auto_now=True, verbose_name='Last Modified')),
                ('Name', models.TextField(blank=True, verbose_name='Property name')),
                ('IsChecked', models.BooleanField(default=False, verbose_name='Is Checked')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
