# Generated by Django 2.0 on 2020-03-23 17:54

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('designer', '0002_taskproperty'),
    ]

    operations = [
        migrations.AddField(
            model_name='taskproperty',
            name='Owner',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='designer.Profile'),
        ),
        migrations.AddField(
            model_name='taskproperty',
            name='Process',
            field=models.TextField(blank=True, verbose_name='Process name'),
        ),
        migrations.AddField(
            model_name='taskproperty',
            name='Task',
            field=models.TextField(blank=True, verbose_name='Task name'),
        ),
    ]
