# Generated by Django 2.0 on 2020-03-23 18:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('designer', '0003_auto_20200323_1754'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='taskproperty',
            name='Process',
        ),
        migrations.RemoveField(
            model_name='taskproperty',
            name='Task',
        ),
        migrations.AddField(
            model_name='taskproperty',
            name='From',
            field=models.TextField(blank=True, verbose_name='Form name'),
        ),
    ]
