# Generated by Django 2.0 on 2020-03-23 18:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('designer', '0004_auto_20200323_1807'),
    ]

    operations = [
        migrations.RenameField(
            model_name='taskproperty',
            old_name='From',
            new_name='Form',
        ),
    ]
