# Generated by Django 2.1.2 on 2018-10-03 09:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('textis', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Syllables',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.TextField(verbose_name='Syllables Text')),
            ],
        ),
        migrations.DeleteModel(
            name='Syllabus',
        ),
    ]
