# Generated by Django 2.1.2 on 2018-10-23 09:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('textis', '0002_auto_20181003_0917'),
    ]

    operations = [
        migrations.CreateModel(
            name='WordCompare',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('word1', models.CharField(max_length=100, verbose_name='Word1')),
                ('word2', models.CharField(max_length=100, verbose_name='Word2')),
            ],
        ),
    ]
